name: neuza
services:
  frontend:
    container_name: neuza-frontend
    hostname: neuza-frontend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3080:3080"
    volumes:
      - .:/app