x-project-name: 'NEUZA'
services:
  # backend:
  #   image: cosmtrek/air
  #   build:
  #     context: /backend
  #     dockerfile: Dockerfile
  #   working_dir: /app
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app

  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3080:3080"
    volumes:
      - ./frontend:/app

  # postgres:
  #   image: "postgres:latest"
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./database:/var/lib/postgresql/data