name: neuza
services:
  database:
      image: "postgres:latest"
      container_name: neuza-database
      hostname: neuza-database
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - .:/var/lib/postgresql/data